[versions]
textile = "1.0.0-beta.8"
omnicore = "1.0.0-beta.38"

[libraries]
textile = { group = "dev.deftu", name = "textile", version.ref = "textile" }
omnicore = { group = "dev.deftu", name = "omnicore", version.ref = "omnicore" }